language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6

env:
  global:
    # $SQLANYWHERE_16_GDRIVE_ID
    - secure: "LmrTaUkqHEOdtet7u0ITxsfyQgLzu0cEBV5/UpLd8P+YmAyVEdTvnarB6s9drO+BbLRkpxeP2ZR7BXX4BTHDOsGPZz53sxQiWzGAGP8Z6gNZPM1S4dMaaMm1b4BZtiMioeXKDtPQmZ105sEQh1LneLiCcIzNgeJW3BnhA8NddC8="
    - LD_LIBRARY_PATH=`pwd`/sqlanywhere/lib64
    - SQLANY12=`pwd`/sqlanywhere
    - SQLANY16=`pwd`/sqlanywhere
  matrix:
    - SQLANYWHERE_GDRIVE_ID=$SQLANYWHERE_16_GDRIVE_ID

install: ./setup.sh
