language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6

env:
  global:
    - secure: "KZKTOIWY6O3VzbsSKK5SPgJB6dBIvsJiOmq9oWSadC5HnV+ZdG9AUnDHAGq8QCOXp1EKr/eLalYzkvdK7k/rvZmHQAM5JZKlA49GSxVIvApVRgeETbmScVev68pfghKYxYTixyA7KuNkGu9htXEAZc3nuKPTwRavQnt6Zuf4VyU="
  matrix:
    - SQLANYWHERE_GDRIVE_ID=$SQLANYWHERE_16_GDRIVE_ID SQLANY16=`pwd`/sqlanywhere16 LD_LIBRARY_PATH=`pwd`/sqlanywhere16/lib64

install: ./setup.sh
