language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6

env:
  global:
    # $SQLANYWHERE_12_GDRIVE_ID
    - secure: "HqkFViQP2aLeKiVHYUJ7HSxBkI5umm+BS63WuzSCniYkJjwaeqlzJ4HbsKsjOZDZGP+IVVWNzZbt/b/0nnDjkpRZbHKjR1FbGJ7UtOzYjmseY9F84gXs6nPmEQSeF8xCd+nlMxDS38ZiwMj8YRv5StWD3WAME9rCAs8KGKRwMiE="
    # $SQLANYWHERE_16_GDRIVE_ID
    - secure: "BNdCXgiF/weNYYgltVIFmkK1tnVUlNkjWeU8khpbQdNQyyqIoLHOPPG9lRttUbqvlJg2Tda27/Qn6/ZEaPBR9N/4TXLKxYzsj5fcHMXCuo/VN9Wchg12BWVx9GuOp+MqVKT91Ky/t7uL/wNURUehgpjuC5hD2fAugtiUqWi/8wo="
    - LD_LIBRARY_PATH=`pwd`/sqlanywhere/lib64
    - SQLANY16=`pwd`/sqlanywhere
  matrix:
    - SQLANYWHERE_GDRIVE_ID=$SQLANYWHERE_12_GDRIVE_ID
    - SQLANYWHERE_GDRIVE_ID=$SQLANYWHERE_16_GDRIVE_ID

install: ./setup.sh
