language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6

env:
  global:
    - secure: "d/I6P6DHa5/Liqy2Ok42oDMrB0U/tf+ET4VYwwxoa41lZOcDk75pmpfrJheoejPhyNCP071dXVGsdMc+dvGHDqMVvTqEGYdXXF6drHu2xFtUYzyDmJukbRRwYX9mhVwPaboCXG2h7FZMEZDpyryrrU5Q2SmMbAyWnnMY5VZ1Esg="
  matrix:
    - SQLANYWHERE_GDRIVE_ID=$SQLANYWHERE_16_GDRIVE_ID SQLANY16=`pwd`/sqlanywhere16 LD_LIBRARY_PATH=`pwd`/sqlanywhere16/lib64

install: ./setup.sh
