language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6

env:
  global:
    - secure: "NdFKGCQVeW7REJLPNl3lw10xn3OvQYMo+7dhVTvfZErq/geDYQDPD9V5qKqvrQscJ5ptKp/Y2HESnLQUsKQS13pT7ZZVnjNwjTQ7zaBV7N43MprN9K7zU7sUgZLznrrr5QNG449qB4vNVGpT2ImOI+/7xXXboqfX6yKtWDxloyE="
  matrix:
    - SQLANYWHERE_GDRIVE_ID=$SQLANYWHERE_16_GDRIVE_ID SQLANY16=`pwd`/sqlanywhere16 LD_LIBRARY_PATH=`pwd`/sqlanywhere16/lib64

install: ./setup.sh
